M48
; DRILL file KiCad 10.0.1 date 2026-05-24T16:41:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-24T16:41:54-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X132.425Y-82.705
X132.425Y-129.655
X156.935Y-82.705
X156.935Y-129.655
M30
